### ISSUE TITLE
utPLSQL integration

### ISSUE THREAD

**Issue by Pazus** [s-oravec/quilt#2]
Hi, I'm a developer of utPLSQL v3 testing framework - https://github.com/utPLSQL/utPLSQL

We have a great bunch of testing stuff including native CI integration, different test reporting format, coverage reporting (also based on `dbms_profiler`). Would you like to implement your great utility as a reporter plugin for the framework? I'm sure it is going to be a great addition!

If you are interested - let me know, we'll find a way to collaborate!

**Comment by s-oravec** [comment]
let's talk on slack
